### ISSUE TITLE
Build failed "ERR_MODULE_NOT_FOUND"

### ISSUE THREAD

**Issue by Lucas-Gruber** [sidebase/nuxt-prisma#5]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `extends`, `auth`, `colorMode`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `nuxt-svgo@1.1.0`, `@huntersofbook/naive-ui-nuxt@0.5.1`, `@sidebase/nuxt-auth@0.3.2`, `@nuxtjs/color-mode@3.2.0`, `@vueuse/nuxt@9.9.0`
- Build Modules:    `-`

### Describe the bug

When i try to start the production env after building the Nuxt App, it fails with following Error Message:

```bash
start
NODE_ENV=production node .output/server/index.mjs

node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/[...]/.output/server/node_modules/@sidebase/nuxt-prisma/nuxt-prisma/server/middleware/0.prisma' imported from /Users/[...]/.output/server/index.mjs
Did you mean to import @sidebase/nuxt-prisma/nuxt-prisma/server/middleware/0.prisma.js?
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:418:11)
    at moduleResolve (node:internal/modules/esm/resolve:983:10)
    at defaultResolve (node:internal/modules/esm/resolve:1080:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by BracketJohn** [comment]
Hey @Lucas-Gruber 👋 

Thank you for reporting this ❤️ We're looking into this, at the moment it looks like we'll deprecate this nuxt-layer in favor of "natively" integrating prisma: Integrating it is quite easy and just requires a couple of files + the layers approach we chose here still has some flaws.

We'll start deprecation by updating the behvaior of `create-sidebase`: https://github.com/sidebase/create-sidebase/pull/5

If this works out well, we'll start with the phase-out of nuxt-prisma by recommending `create-sidebase` to get started with projects that need prisma in the readme here.

Then we'll deprecate this repo + the corresponding package at some point.

Sorry for this (sad) information -> if you want to I can have a look at your setup to help you setup prisma correctly in your project ❤️ Just let me know here or on discord: https://discord.gg/9MUHR8WT9B

**Comment by Wr4ngla** [comment]
Is there a workaround for this issue at the moment? I am having the same issue.

**Comment by BracketJohn** [comment]
Hey @Wr4ngla 👋 

Thanks for the q - you can natively integrate it yourself to avoid this. For this you need to:
- create one file `server/middleware/prisma.ts` with content [1]
- install depoendencies:
  - @prisma/client
  - prisma (as dev)


and it should work!

Alternatively you can use:
```
# also works with `pnpm`, `yarn`
# choose Merino, then choose Prisma ORM
npm create sidebase@latest
```

**Comment by BracketJohn** [comment]
closing this, please add a new comment or ask something in #6 if it is related to the deprecation. Thanks ❤️
